# -*- coding: utf-8 -*-
"""automate_Amar-Luthfi.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ebgc1r-fuHNXbMqD-2TeB5X5QkQR30lX
"""

import os
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

def run_preprocessing(input_path, output_dir):
    print(f"[INFO] Memulai proses otomatisasi data dari: {input_path}")

    if not os.path.exists(input_path):
        raise FileNotFoundError(f"File dataset mentah tidak ditemukan di jalur: {input_path}")

    # Memuat Dataset Mentah
    df = pd.read_csv(input_path)

    # Penanganan Outlier (Sesuai Cell Eksperimen Anda)
    df = df[df['person_age'] <= 100]
    df = df[df['person_emp_length'] <= 60]

    # Memisahkan Fitur (X) dan Target (y)
    X = df.drop('loan_status', axis=1)
    y = df['loan_status']

    # Train-Test Split dengan Stratifikasi (Menjaga Keseimbangan Kelas)
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )

    # Definisi Fitur Sesuai Data
    numerical_features = [
        'person_age', 'person_income', 'person_emp_length',
        'loan_amnt', 'loan_int_rate', 'loan_percent_income',
        'cb_person_cred_hist_length'
    ]
    categorical_features = [
        'person_home_ownership', 'loan_intent',
        'loan_grade', 'cb_person_default_on_file'
    ]

    # Membangun Pipeline Preprocessing
    numerical_transformer = Pipeline(steps=[
        ('imputer', SimpleImputer(strategy='median')),
        ('scaler', StandardScaler())
    ])

    categorical_transformer = Pipeline(steps=[
        ('imputer', SimpleImputer(strategy='most_frequent')),
        # Menggunakan sparse_output=False saat konversi DataFrame dengan scikit-learn (safe)
        ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
    ])

    preprocessor = ColumnTransformer(transformers=[
        ('num', numerical_transformer, numerical_features),
        ('cat', categorical_transformer, categorical_features)
    ])

    # Eksekusi Fit & Transform Data Training dan Test
    X_train_processed = preprocessor.fit_transform(X_train)
    X_test_processed = preprocessor.transform(X_test)

    # Mengembalikan Hasil Transformasi Menjadi DataFrame Berlabel
    feature_names = preprocessor.get_feature_names_out()
    X_train_processed_df = pd.DataFrame(X_train_processed, columns=feature_names)
    X_test_processed_df = pd.DataFrame(X_test_processed, columns=feature_names)

    # Menyimpan Seluruh Hasil Pemrosesan ke Folder Target (Kewajiban Kriteria 1)
    os.makedirs(output_dir, exist_ok=True)

    X_train_processed_df.to_csv(os.path.join(output_dir, 'X_train_processed.csv'), index=False)
    X_test_processed_df.to_csv(os.path.join(output_dir, 'X_test_processed.csv'), index=False)
    y_train.to_csv(os.path.join(output_dir, 'y_train_processed.csv'), index=False)
    y_test.to_csv(os.path.join(output_dir, 'y_test_processed.csv'), index=False)

    print(f"[SUKSES] Seluruh file preprocessing berhasil disimpan di: {output_dir}")

if __name__ == "__main__":
    # Mengambil Dataset Mentah (awal)
    INPUT_FILE = "dataset_raw/credit_risk_dataset.csv"

    # Menyimpan Dataset hasil Presprocessing
    OUTPUT_DIRECTORY = "dataset_preprocessing"

    run_preprocessing(INPUT_FILE, OUTPUT_DIRECTORY)